### ISSUE TITLE
Stuff to work on

### ISSUE THREAD

**Issue by BrainMaestro** [skaex/mayo#1]
Hwy @SkaeX. Would it be possible to split up tasks into small units so we can start picking them up?

Also, I thought you suggested us using Angular 2 or something else?

**Comment by skaex** [comment]
I thought about it again and decided Angular (majorly because of development time) should come in the next release. For now, I have started using just the native django templates. I will create a project on the [project tab](https://github.com/SkaeX/mayo/projects) and add some tasks. Thanks a lot @BrainMaestro .
